### ISSUE TITLE
importC gain?

### ISSUE THREAD

**Issue by cyrusmsk** [nordlow/gmp-d#14]
Could this project get gain from importC?
To have automatically all methods from GMP?

**Comment by nordlow** [comment]
Yes it would. Feel free to give it a try. 😊

**Comment by nordlow** [comment]
Thanks.

**Comment by cyrusmsk** [comment]
Thanks

**Comment by nordlow** [comment]
I believe you should close this issue when a solution has been merged to master. Not sooner.
